### ISSUE TITLE
Removed projects and repositories should be disappeared after some time

### ISSUE THREAD

**Issue by minwoox** [line/centraldogma#85] opened 2017-11-07 09:38 UTC
Currently, removed projects and repositories are not removed, but just renamed with having the suffix of `.removed`.
We need to provide a way to remove them permanently when `N`(configurable, can be 0) days has passed.

**Comment by trustin** [comment] 2017-11-09 03:17
Duplicate of #47

**Closed by trustin** 2017-11-09 03:17 UTC
Labels: new-feature
